
[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F12"

[general]
import = ["/Users/jingkaiooi/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "Menlo"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[keyboard]
