
# [[keyboard.bindings]]
# action = "ToggleFullscreen"
# key = "F12"

[general]
import = ["/Users/jingkaiooi/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "Menlo"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
# args = ["-l", "-c", "tmux a || tmux"]
# program = "tmux"
# args = ["a || tmux"]

[window]
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "F12", action = "ToggleFullScreen" },
  { key = "F", mods = "Control|Shift", chars = "tmux-sessionizer\u000D" }
]

