-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--
-- vim.opt.clipboard = "unnamedplus"
-- vim.g.snacks_animate = false
-- vim.g.autoformat = false
-- vim.api.nvim_set_hl(0, "Normal", { fg = "#000000", default = true })
