require("kai.plugins-setup")
require("kai.core.options")
require("kai.core.keymaps")
require("kai.core.colorscheme")
require("kai.plugins.comment")
require("kai.plugins.nvim-tree")
require("kai.plugins.lualine")
require("kai.plugins.telescope")
